---
- hosts: all
  become: yes
  tasks:
    - name: add apt key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80 
        id: EA312927
    - name: add repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
    - name: update packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: yes
    - name: install mongo
      apt:
        name: mongodb-org
        state: present
    - name: start and enable mongo 
      service:
        name: mongod
        enabled: yes
        state: started