---
- name: configure
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.132.0.48
  tasks:
    - name: mongo config
      become: yes
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongod
    - name: add unit file
      become: yes
      copy: 
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma
    - name: add config
      template:
        src: templates/db_config.j2
        dest: /home/knuteg/db_config
      tags: app-tag
    - name: enable puma
      become: yes
      systemd:
        name: puma
        enabled: yes
      tags: app-tag
    - name: get app
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/knuteg/reddit
        version: monolith
      tags: deploy-tag
      notify: reload puma
    - name: bundle
      bundler:
        state: present
        chdir: /home/knuteg/reddit
      tags: deploy-tag
        
  handlers:
  - name: restart mongod
    become: yes
    service:
      name: mongod
      state: restarted
  - name: reload puma
    become: yes
    systemd:
      name: puma
      state: restarted


